### ISSUE TITLE
OpenLauncher Support

### ISSUE THREAD

**Issue by mueller-ma** [numixproject/com.numix.icons_circle#49]
OpenLauncher can apply this theme, so there is only a link missing in the numix app to the openlauncher settings. https://github.com/OpenLauncherTeam/openlauncher

**Comment by bil-elmoussaoui** [comment]
I'm going to implement https://github.com/numixproject/com.numix.icons_circle/issues/46 which will use Candy Bar Library, this way we will concentrate on create icons instead of improving/updating the application and supporting more launchers. So if Candy Bar already support Open Launcher, once the migration is done this issue will be fixed too. Otherwise, you can report it upstream :+1:

**Comment by mueller-ma** [comment]
https://github.com/danimahardhika/candybar-library/issues/46
